version: '3.8'

networks:
  corp:
    driver: bridge

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:${BACKEND_POSTGRES_VERSION}
    restart: always
    ports:
      - ${BACKEND_POSTGRES_EXPOSE_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD?:error}
      BACKEND_POSTGRES_VERSION: ${BACKEND_POSTGRES_VERSION?:error}
      BACKEND_POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD?:error}
      BACKEND_POSTGRES_EXPOSE_PORT: ${BACKEND_POSTGRES_EXPOSE_PORT?:error}
    networks:
      - corp

  backend:
    container_name: backend
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/backend/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: backend:nx-dev
    ports:
      - ${BACKEND_EXPOSE_PORT}:4939
    depends_on:
      - postgresdb
    env_file:
      - .env
    environment:
      NODE_ENV: 'development'
      PORT: 4939
      BACKEND_EXPOSE_PORT: ${BACKEND_EXPOSE_PORT?:error}
    networks:
      - corp
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/frontend/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: frontend:nx-dev
    ports:
      - ${FRONTEND_EXPOSE_PORT}:80
    env_file:
      - .env
    environment:
      NODE_ENV: 'development'
      PORT: 4900
      FRONTEND_EXPOSE_PORT: ${FRONTEND_EXPOSE_PORT?:error}
    networks:
      - corp
    restart: on-failure
